version: 1
runtime: python27
api_version: 1
threadsafe: true
application: ga2optly

handlers:
- url: /.*
  script: ga2optly.app

libraries:
- name: webapp2
  version: latest
- name: ssl
  version: latest